[pytest]
markers =
    unit: unit tests
    integration: integration tests
    e2e: end-to-end tests
addopts = -ra
filterwarnings =
    ignore:Type google\._upb\._message\..* uses PyType_Spec with a metaclass that has custom tp_new\.:DeprecationWarning
    ignore:The 'app' shortcut is now deprecated\. Use the explicit style 'transport=WSGITransport\(app=...\)' instead\.:DeprecationWarning
